export enum LabTestsType {
	ButtedLooseLeafTest = 1,
	DegsTest = 2,
	DensityTest = 3,
	FinesTest = 4,
	FlagOnStemTest = 5,
	InlineDataTest = 6,
	InlineHsTest = 7,
	LeavesTest = 8,
	LooseLeafTest = 9,
	MoistureAndTempTest = 10,
	NtrmGreenTest = 11,
	NtrmInlineTest = 12,
	NtrmProductTest = 13,
	SandTest = 14,
	ShortStemTest = 15,
	StemDiameterTest = 16,
	StemInScrapTest = 17,
	StemLengthTest = 18,
	TipsTest = 19,
	StemAuditTest = 20,
	BundleBusterTest = 21,
	ShakerEfficiencyTest = 22
}
